language: node_js
node_js:
  - '10'
cache:
  yarn: true
script:
  - PUBLIC_URL=$PUBLIC_URL GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: build
  on:
    branch: master
